package main

import "testing"

func TestBlockedExcludes400(t *testing.T) {
	// 400 é request malformado, não WAF — nunca deve contar como bloqueio.
	if blocked(400) {
		t.Error("400 não deveria ser tratado como bloqueio de WAF")
	}
	for _, s := range []int{403, 406, 429, 501, 503} {
		if !blocked(s) {
			t.Errorf("HTTP %d deveria contar como bloqueio de WAF", s)
		}
	}
	for _, s := range []int{200, 301, 302, 404, 500} {
		if blocked(s) {
			t.Errorf("HTTP %d não deveria contar como bloqueio de WAF", s)
		}
	}
}

func TestMatchVendor(t *testing.T) {
	cases := []struct {
		src  string
		want string
	}{
		{"server: cloudflare\ncf-ray: abc123\n", "Cloudflare"},
		{"x-sucuri-id: 12345\n", "Sucuri"},
		{"x-iinfo: 1-2-3\nset-cookie: incap_ses_123=xyz\n", "Imperva Incapsula"},
		{"the requested url was rejected. please consult with your administrator. support id: 999", "F5 BIG-IP ASM"},
		{"this error was generated by mod_security", "ModSecurity"},
		{"server: nginx\ncontent-type: text/html\n<html><body>ok</body></html>", ""},
	}
	for _, c := range cases {
		got, _ := matchVendor(c.src)
		if got != c.want {
			t.Errorf("matchVendor(%q) = %q, quer %q", c.src, got, c.want)
		}
	}
}

func TestMatchVendorNoFalsePositiveOnPlainSite(t *testing.T) {
	// Um site comum atrás de nginx, sem WAF, não pode casar com nenhum vendor.
	src := "server: nginx/1.18.0\ncontent-type: text/html; charset=utf-8\ndate: mon, 01 jan 2026 00:00:00 gmt\n<!doctype html><html><head><title>home</title></head></html>"
	if v, _ := matchVendor(src); v != "" {
		t.Errorf("site comum casou com vendor %q — falso positivo", v)
	}
}
